apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: pong
  labels:
    app: k8slab
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi