apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: pong
spec:
  selector:
    matchLabels:
      app: k8slab
  replicas: 1
  template:
    metadata:
      labels:
        app: k8slab
    spec:
      containers:
      - name: redis
        image: redis:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        # data volume where redis writes data
        volumeMounts:
        - name: data
          mountPath: /data
          readOnly: false
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: redis-data